---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  chart:
    spec:

      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
      interval: 5m