---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: portainer.example.io
          paths:
            - path: /
