---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m0s
  path: ./Addons/Environments/Sample/portainer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system