---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  chart:
    spec:
      version: "4.7.2"
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      interval: 10m